# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/wilcox-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/wilcox-common/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/samsung/wilcox-common/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
    vendor/samsung/wilcox-common/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/samsung/wilcox-common/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/samsung/wilcox-common/proprietary/bin/thermald:system/bin/thermald \
    vendor/samsung/wilcox-common/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/samsung/wilcox-common/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/samsung/wilcox-common/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
    vendor/samsung/wilcox-common/proprietary/lib/libExtendedExtractor.so:system/lib/libExtendedExtractor.so \
    vendor/samsung/wilcox-common/proprietary/lib/libSHIMDivxDrm.so:system/lib/libSHIMDivxDrm.so \
    vendor/samsung/wilcox-common/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/samsung/wilcox-common/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/samsung/wilcox-common/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/samsung/wilcox-common/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/samsung/wilcox-common/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/egl/libGLESv2S3D_adreno.so:system/vendor/lib/egl/libGLESv2S3D_adreno.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/libc2d30.so:system/vendor/lib/libc2d30.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/libllvm-a3xx.so:system/vendor/lib/libllvm-a3xx.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/libOpenVG.so:system/vendor/lib/libOpenVG.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/samsung/wilcox-common/proprietary/lib/libI420colorconvert.so:system/lib/libI420colorconvert.so \
    vendor/samsung/wilcox-common/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/samsung/wilcox-common/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/samsung/wilcox-common/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/wilcox-common/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/wilcox-common/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/wilcox-common/proprietary/lib/libcordon.so:system/lib/libcordon.so \
    vendor/samsung/wilcox-common/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/samsung/wilcox-common/proprietary/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/wilcox-common/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/samsung/wilcox-common/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/wilcox-common/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/samsung/wilcox-common/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/wilcox-common/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/wilcox-common/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/samsung/wilcox-common/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/wilcox-common/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/wilcox-common/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/wilcox-common/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/samsung/wilcox-common/proprietary/lib/libtime_genoff.so:system/lib/libtime_genoff.so \
    vendor/samsung/wilcox-common/proprietary/lib/libgeofence.so:system/lib/libgeofence.so \
    vendor/samsung/wilcox-common/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/samsung/wilcox-common/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
    vendor/samsung/wilcox-common/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/samsung/wilcox-common/proprietary/lib/hw/camera.vendor.msm8960.so:system/lib/hw/camera.vendor.msm8960.so \
    vendor/samsung/wilcox-common/proprietary/lib/libadsprpc.so:system/lib/libadsprpc.so \
    vendor/samsung/wilcox-common/proprietary/lib/libchromatix_imx175_antishake.so:system/lib/libchromatix_imx175_antishake.so \
    vendor/samsung/wilcox-common/proprietary/lib/libchromatix_imx175_default_video.so:system/lib/libchromatix_imx175_default_video.so \
    vendor/samsung/wilcox-common/proprietary/lib/libchromatix_imx175_lls.so:system/lib/libchromatix_imx175_lls.so \
    vendor/samsung/wilcox-common/proprietary/lib/libchromatix_imx175_preview.so:system/lib/libchromatix_imx175_preview.so \
    vendor/samsung/wilcox-common/proprietary/lib/libchromatix_imx175_zsl.so:system/lib/libchromatix_imx175_zsl.so \
    vendor/samsung/wilcox-common/proprietary/lib/libchromatix_imx175_zsl_drama.so:system/lib/libchromatix_imx175_zsl_drama.so \
    vendor/samsung/wilcox-common/proprietary/lib/libchromatix_imx175_zsl_panorama.so:system/lib/libchromatix_imx175_zsl_panorama.so \
    vendor/samsung/wilcox-common/proprietary/lib/libchromatix_s5k3h5xa_antishake.so:system/lib/libchromatix_s5k3h5xa_antishake.so \
    vendor/samsung/wilcox-common/proprietary/lib/libchromatix_s5k3h5xa_default_video.so:system/lib/libchromatix_s5k3h5xa_default_video.so \
    vendor/samsung/wilcox-common/proprietary/lib/libchromatix_s5k3h5xa_lls.so:system/lib/libchromatix_s5k3h5xa_lls.so \
    vendor/samsung/wilcox-common/proprietary/lib/libchromatix_s5k3h5xa_preview.so:system/lib/libchromatix_s5k3h5xa_preview.so \
    vendor/samsung/wilcox-common/proprietary/lib/libchromatix_s5k3h5xa_zsl.so:system/lib/libchromatix_s5k3h5xa_zsl.so \
    vendor/samsung/wilcox-common/proprietary/lib/libchromatix_s5k3h5xa_zsl_drama.so:system/lib/libchromatix_s5k3h5xa_zsl_drama.so \
    vendor/samsung/wilcox-common/proprietary/lib/libchromatix_s5k3h5xa_zsl_panorama.so:system/lib/libchromatix_s5k3h5xa_zsl_panorama.so \
    vendor/samsung/wilcox-common/proprietary/lib/libchromatix_s5k6a3yx_default_video.so:system/lib/libchromatix_s5k6a3yx_default_video.so \
    vendor/samsung/wilcox-common/proprietary/lib/libchromatix_s5k6a3yx_preview.so:system/lib/libchromatix_s5k6a3yx_preview.so \
    vendor/samsung/wilcox-common/proprietary/lib/libchromatix_s5k6a3yx_smart_stay.so:system/lib/libchromatix_s5k6a3yx_smart_stay.so \
    vendor/samsung/wilcox-common/proprietary/lib/libchromatix_s5k6a3yx_vt.so:system/lib/libchromatix_s5k6a3yx_vt.so \
    vendor/samsung/wilcox-common/proprietary/lib/libchromatix_s5k6a3yx_vt_hd.so:system/lib/libchromatix_s5k6a3yx_vt_hd.so \
    vendor/samsung/wilcox-common/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/samsung/wilcox-common/proprietary/lib/libimage-jpeg-dec-omx-comp.so:system/lib/libimage-jpeg-dec-omx-comp.so \
    vendor/samsung/wilcox-common/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/samsung/wilcox-common/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/samsung/wilcox-common/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/samsung/wilcox-common/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/samsung/wilcox-common/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/samsung/wilcox-common/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/samsung/wilcox-common/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/samsung/wilcox-common/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/samsung/wilcox-common/proprietary/lib/libmmcamera_plugin.so:system/lib/libmmcamera_plugin.so \
    vendor/samsung/wilcox-common/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/samsung/wilcox-common/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/samsung/wilcox-common/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/samsung/wilcox-common/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/samsung/wilcox-common/proprietary/lib/libmmmpod.so:system/lib/libmmmpod.so \
    vendor/samsung/wilcox-common/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/samsung/wilcox-common/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/samsung/wilcox-common/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/wilcox-common/proprietary/lib/libTsAccm.so:system/lib/libTsAccm.so \
    vendor/samsung/wilcox-common/proprietary/lib/libTsAwb.so:system/lib/libTsAwb.so \
    vendor/samsung/wilcox-common/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/samsung/wilcox-common/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/samsung/wilcox-common/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/samsung/wilcox-common/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/samsung/wilcox-common/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/samsung/wilcox-common/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/samsung/wilcox-common/proprietary/lib/libWVStreamControlAPI_L3.so:system/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/wilcox-common/proprietary/lib/libwvm.so:system/lib/libwvm.so
